### ISSUE TITLE
Make fails to complete with compilation error

### ISSUE THREAD

**Issue by kshtsk** [beanstalkd/beanstalkd#345]
Faced the issue while trying to compile on with cc (SUSE Linux) 4.8.5 om Leap 42.2

> make
cc -Wall -Werror -Wformat=2 -g    -c -o linux.o linux.c
cc -Wall -Werror -Wformat=2 -g    -c -o conn.o conn.c
cc -Wall -Werror -Wformat=2 -g    -c -o file.o file.c
cc -Wall -Werror -Wformat=2 -g    -c -o heap.o heap.c
cc -Wall -Werror -Wformat=2 -g    -c -o job.o job.c
job.c: In function ‘store_job’:
job.c:37:5: error: call to function ‘rehash’ without a real prototype [-Werror=unprototyped-calls]
     if (all_jobs_used > (all_jobs_cap << 2)) rehash(1);
     ^
job.c:17:13: note: ‘rehash’ was declared here
 static void rehash();
             ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'job.o' failed
make: *** [job.o] Error 1

**Comment by kshtsk** [comment]
Possible fis is like:
diff --git a/job.c b/job.c
index 32487da..e1f7768 100644
--- a/job.c
+++ b/job.c
@@ -14,7 +14,7 @@ static size_t all_jobs_used = 0;
 
 static int hash_table_was_oom = 0;
 
-static void rehash();
+static void rehash(int);
 
 static int
 _get_job_hash_index(uint64 job_id)
