### ISSUE TITLE
Build failure with -Wgnu/clang

### ISSUE THREAD

**Issue by jbergstroem** [beanstalkd/beanstalkd#110]
beanstalkd currently fails to build with clang 3.0/3.1 - tested on fbsd9-release and  OS X.

``` bash
# CC=clang gmake   
clang -Wall -Werror   -c -o conn.o conn.c
In file included from conn.c:8:
./dat.h:279:16: error: field 'reserved_jobs' with variable sized type 'struct job' not at the end of a struct or class is a GNU
      extension [-Werror,-Wgnu]
    struct job reserved_jobs; // linked list header
               ^
1 error generated.
gmake: *** [conn.o] Error 1
```
