### ISSUE TITLE
unable to build with optimizing levels on Linux

### ISSUE THREAD

**Issue by sergeyklay** [beanstalkd/beanstalkd#423]
This error occurs only on turn full optimization eg `CFLAGS="-O3"`.

```bash
$ export CFLAGS="-O3"
$ export MAKEJOBS="-j$(getconf _NPROCESSORS_ONLN)"
```

```bash
$ make $MAKEJOBS
gcc -O3 -Wall -Werror -Wformat=2 -g   -c -o linux.o linux.c
gcc -O3 -Wall -Werror -Wformat=2 -g   -c -o conn.o conn.c
gcc -O3 -Wall -Werror -Wformat=2 -g   -c -o file.o file.c
file.c: In function ‘filewclose’:
file.c:536:9: error: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Werror=unused-result]
         (void)ftruncate(f->fd, f->w->filesize - f->free);
         ^
cc1: all warnings being treated as errors
make: *** [file.o] Error 1
```

```bash
$ make bench
gcc -O3 -Wall -Werror -Wformat=2 -g   -c -o testheap.o testheap.c
gcc -O3 -Wall -Werror -Wformat=2 -g   -c -o testjobs.o testjobs.c
gcc -O3 -Wall -Werror -Wformat=2 -g   -c -o testserv.o testserv.c
gcc -O3 -Wall -Werror -Wformat=2 -g   -c -o testutil.o testutil.c
ct/gen testheap.o testjobs.o testserv.o testutil.o  >ct/_ctcheck.c.part
mv ct/_ctcheck.c.part ct/_ctcheck.c
gcc -O3 -Wall -Werror -Wformat=2 -g   -c -o ct/_ctcheck.o ct/_ctcheck.c
gcc -O3 -Wall -Werror -Wformat=2 -g   -c -o ct/ct.o ct/ct.c
ct/ct.c: In function ‘writetokens’:
ct/ct.c:543:18: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
             write(wjobfd, &c, 1); /* ignore error; nothing we can do anyway */
                  ^
ct/ct.c: In function ‘runbenchn’:
ct/ct.c:326:14: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
         write(durfd, &bdur, sizeof bdur);
              ^
ct/ct.c:327:14: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
         write(durfd, &bbytes, sizeof bbytes);
              ^
cc1: all warnings being treated as errors
make: *** [ct/ct.o] Error 1
```

All warnings being treated as errors because `-Wall -Werror`. The same with `O2`.

Ubuntu Trusty, gcc 4.8.4

/cc @kr @ysmolsky

**Comment by sergeyklay** [comment]
As I see all errors related to "-Werror=unused-result" so it is easy to fix

**Comment by ysmolsky** [comment]
Works fine on macOS 10.14.5:
```
~/d/beanstalkd (master *%=) % export CFLAGS="-O3"
~/d/beanstalkd (master *%=) % export MAKEJOBS="-j$(getconf _NPROCESSORS_ONLN)"
~/d/beanstalkd (master *%=) % make $MAKEJOBS
```
I tried both 6225c62 and master (4b452b4) tips.

**Comment by sergeyklay** [comment]
Let me recheck again.

**Comment by sergeyklay** [comment]
@ysmolsky Did you use Clang on macOS?

**Comment by ysmolsky** [comment]
Yes, clang builds it fine.
```
~/d/beanstalkd (master %=) % cc -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Also I have installed gcc8 and tried to build:
```
~/d/beanstalkd (master %=) % CC=gcc-mp-8 make
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o darwin.o darwin.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o conn.o conn.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o file.o file.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o heap.o heap.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o job.o job.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o ms.o ms.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o net.o net.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o primes.o primes.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o prot.o prot.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o sd-daemon.o sd-daemon.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o serv.o serv.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o time.o time.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o tube.o tube.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o util.o util.c
./verc.sh >vers.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o vers.o vers.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o walg.o walg.c
gcc-mp-8 -O3 -Wall -Werror -Wformat=2 -g   -c -o main.o main.c
gcc-mp-8   -o beanstalkd darwin.o conn.o file.o heap.o job.o ms.o net.o primes.o prot.o sd-daemon.o serv.o time.o tube.o util.o vers.o walg.o main.o
```

```
~/d/beanstalkd (master %=) % gcc-mp-8 -v
Using built-in specs.
COLLECT_GCC=gcc-mp-8
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin18/8.3.0/lto-wrapper
Target: x86_64-apple-darwin18
Configured with: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_gcc8/gcc8/work/gcc-8.3.0/configure --prefix=/opt/local --build=x86_64-apple-darwin18 --enable-languages=c,c++,objc,obj-c++,lto,fortran --libdir=/opt/local/lib/gcc8 --includedir=/opt/local/include/gcc8 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-8 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-8 --with-gxx-include-dir=/opt/local/include/gcc8/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-build-config=bootstrap-debug --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --disable-tls --with-pkgversion='MacPorts gcc8 8.3.0_4' --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
Thread model: posix
gcc version 8.3.0 (MacPorts gcc8 8.3.0_4)```

**Comment by sergeyklay** [comment]
Well, there is an issue with pure gcc on linux then. Try to add optimization flags to the build matrix to see the problem.

**Comment by ysmolsky** [comment]
We can fix error in file.c, but errors in ct.c should be fixed in https://github.com/kr/ct/issues/20

**Comment by ysmolsky** [comment]
@sergeyklay can you try now? All errors mentioned above should be fixed by now.
